package com.blgroup.jkl.bean;

import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.ITEM_ID
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.ITEM_CODE
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.ITEM_NAME
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.PROD_CODE
     *
     * @mbggenerated
     */
    private String prodCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.PROD_NAME
     *
     * @mbggenerated
     */
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.STORE_ID
     *
     * @mbggenerated
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.IS_RECOMMEND
     *
     * @mbggenerated
     */
    private String isRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.BAR_TYPE
     *
     * @mbggenerated
     */
    private String barType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.BAR_CODE
     *
     * @mbggenerated
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.SALE_DESC
     *
     * @mbggenerated
     */
    private String saleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.SUPPLIER_CODE
     *
     * @mbggenerated
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.CN_DESC
     *
     * @mbggenerated
     */
    private String cnDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.EN_DESC
     *
     * @mbggenerated
     */
    private String enDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.ITEM_SPEC
     *
     * @mbggenerated
     */
    private String itemSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.EXPIRATION_DATE
     *
     * @mbggenerated
     */
    private Integer expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.WEIGHT
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.GOODS_VALUES
     *
     * @mbggenerated
     */
    private Long goodsValues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.STOCK
     *
     * @mbggenerated
     */
    private Long stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.ITEM_IMAGE
     *
     * @mbggenerated
     */
    private String itemImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.ITEM_CATE
     *
     * @mbggenerated
     */
    private String itemCate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.BRAND_ID
     *
     * @mbggenerated
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.BRAND_NAME
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.ORI_COUNTRY
     *
     * @mbggenerated
     */
    private String oriCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.GOODS_STATUS
     *
     * @mbggenerated
     */
    private String goodsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.IS_DELETED
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_item.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    private String saleSum;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.ITEM_ID
     *
     * @return the value of t_b2b_item.ITEM_ID
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.ITEM_ID
     *
     * @param itemId the value for t_b2b_item.ITEM_ID
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.ITEM_CODE
     *
     * @return the value of t_b2b_item.ITEM_CODE
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.ITEM_CODE
     *
     * @param itemCode the value for t_b2b_item.ITEM_CODE
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.ITEM_NAME
     *
     * @return the value of t_b2b_item.ITEM_NAME
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.ITEM_NAME
     *
     * @param itemName the value for t_b2b_item.ITEM_NAME
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.PROD_CODE
     *
     * @return the value of t_b2b_item.PROD_CODE
     *
     * @mbggenerated
     */
    public String getProdCode() {
        return prodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.PROD_CODE
     *
     * @param prodCode the value for t_b2b_item.PROD_CODE
     *
     * @mbggenerated
     */
    public void setProdCode(String prodCode) {
        this.prodCode = prodCode == null ? null : prodCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.PROD_NAME
     *
     * @return the value of t_b2b_item.PROD_NAME
     *
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.PROD_NAME
     *
     * @param prodName the value for t_b2b_item.PROD_NAME
     *
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.STORE_ID
     *
     * @return the value of t_b2b_item.STORE_ID
     *
     * @mbggenerated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.STORE_ID
     *
     * @param storeId the value for t_b2b_item.STORE_ID
     *
     * @mbggenerated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.IS_RECOMMEND
     *
     * @return the value of t_b2b_item.IS_RECOMMEND
     *
     * @mbggenerated
     */
    public String getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.IS_RECOMMEND
     *
     * @param isRecommend the value for t_b2b_item.IS_RECOMMEND
     *
     * @mbggenerated
     */
    public void setIsRecommend(String isRecommend) {
        this.isRecommend = isRecommend == null ? null : isRecommend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.BAR_TYPE
     *
     * @return the value of t_b2b_item.BAR_TYPE
     *
     * @mbggenerated
     */
    public String getBarType() {
        return barType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.BAR_TYPE
     *
     * @param barType the value for t_b2b_item.BAR_TYPE
     *
     * @mbggenerated
     */
    public void setBarType(String barType) {
        this.barType = barType == null ? null : barType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.BAR_CODE
     *
     * @return the value of t_b2b_item.BAR_CODE
     *
     * @mbggenerated
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.BAR_CODE
     *
     * @param barCode the value for t_b2b_item.BAR_CODE
     *
     * @mbggenerated
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.SALE_DESC
     *
     * @return the value of t_b2b_item.SALE_DESC
     *
     * @mbggenerated
     */
    public String getSaleDesc() {
        return saleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.SALE_DESC
     *
     * @param saleDesc the value for t_b2b_item.SALE_DESC
     *
     * @mbggenerated
     */
    public void setSaleDesc(String saleDesc) {
        this.saleDesc = saleDesc == null ? null : saleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.SUPPLIER_CODE
     *
     * @return the value of t_b2b_item.SUPPLIER_CODE
     *
     * @mbggenerated
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.SUPPLIER_CODE
     *
     * @param supplierCode the value for t_b2b_item.SUPPLIER_CODE
     *
     * @mbggenerated
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.CN_DESC
     *
     * @return the value of t_b2b_item.CN_DESC
     *
     * @mbggenerated
     */
    public String getCnDesc() {
        return cnDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.CN_DESC
     *
     * @param cnDesc the value for t_b2b_item.CN_DESC
     *
     * @mbggenerated
     */
    public void setCnDesc(String cnDesc) {
        this.cnDesc = cnDesc == null ? null : cnDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.EN_DESC
     *
     * @return the value of t_b2b_item.EN_DESC
     *
     * @mbggenerated
     */
    public String getEnDesc() {
        return enDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.EN_DESC
     *
     * @param enDesc the value for t_b2b_item.EN_DESC
     *
     * @mbggenerated
     */
    public void setEnDesc(String enDesc) {
        this.enDesc = enDesc == null ? null : enDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.ITEM_SPEC
     *
     * @return the value of t_b2b_item.ITEM_SPEC
     *
     * @mbggenerated
     */
    public String getItemSpec() {
        return itemSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.ITEM_SPEC
     *
     * @param itemSpec the value for t_b2b_item.ITEM_SPEC
     *
     * @mbggenerated
     */
    public void setItemSpec(String itemSpec) {
        this.itemSpec = itemSpec == null ? null : itemSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.EXPIRATION_DATE
     *
     * @return the value of t_b2b_item.EXPIRATION_DATE
     *
     * @mbggenerated
     */
    public Integer getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.EXPIRATION_DATE
     *
     * @param expirationDate the value for t_b2b_item.EXPIRATION_DATE
     *
     * @mbggenerated
     */
    public void setExpirationDate(Integer expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.UNIT
     *
     * @return the value of t_b2b_item.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.UNIT
     *
     * @param unit the value for t_b2b_item.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.WEIGHT
     *
     * @return the value of t_b2b_item.WEIGHT
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.WEIGHT
     *
     * @param weight the value for t_b2b_item.WEIGHT
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.GOODS_VALUES
     *
     * @return the value of t_b2b_item.GOODS_VALUES
     *
     * @mbggenerated
     */
    public Long getGoodsValues() {
        return goodsValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.GOODS_VALUES
     *
     * @param goodsValues the value for t_b2b_item.GOODS_VALUES
     *
     * @mbggenerated
     */
    public void setGoodsValues(Long goodsValues) {
        this.goodsValues = goodsValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.STOCK
     *
     * @return the value of t_b2b_item.STOCK
     *
     * @mbggenerated
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.STOCK
     *
     * @param stock the value for t_b2b_item.STOCK
     *
     * @mbggenerated
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.ITEM_IMAGE
     *
     * @return the value of t_b2b_item.ITEM_IMAGE
     *
     * @mbggenerated
     */
    public String getItemImage() {
        return itemImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.ITEM_IMAGE
     *
     * @param itemImage the value for t_b2b_item.ITEM_IMAGE
     *
     * @mbggenerated
     */
    public void setItemImage(String itemImage) {
        this.itemImage = itemImage == null ? null : itemImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.ITEM_CATE
     *
     * @return the value of t_b2b_item.ITEM_CATE
     *
     * @mbggenerated
     */
    public String getItemCate() {
        return itemCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.ITEM_CATE
     *
     * @param itemCate the value for t_b2b_item.ITEM_CATE
     *
     * @mbggenerated
     */
    public void setItemCate(String itemCate) {
        this.itemCate = itemCate == null ? null : itemCate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.BRAND_ID
     *
     * @return the value of t_b2b_item.BRAND_ID
     *
     * @mbggenerated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.BRAND_ID
     *
     * @param brandId the value for t_b2b_item.BRAND_ID
     *
     * @mbggenerated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.BRAND_NAME
     *
     * @return the value of t_b2b_item.BRAND_NAME
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.BRAND_NAME
     *
     * @param brandName the value for t_b2b_item.BRAND_NAME
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.ORI_COUNTRY
     *
     * @return the value of t_b2b_item.ORI_COUNTRY
     *
     * @mbggenerated
     */
    public String getOriCountry() {
        return oriCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.ORI_COUNTRY
     *
     * @param oriCountry the value for t_b2b_item.ORI_COUNTRY
     *
     * @mbggenerated
     */
    public void setOriCountry(String oriCountry) {
        this.oriCountry = oriCountry == null ? null : oriCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.GOODS_STATUS
     *
     * @return the value of t_b2b_item.GOODS_STATUS
     *
     * @mbggenerated
     */
    public String getGoodsStatus() {
        return goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.GOODS_STATUS
     *
     * @param goodsStatus the value for t_b2b_item.GOODS_STATUS
     *
     * @mbggenerated
     */
    public void setGoodsStatus(String goodsStatus) {
        this.goodsStatus = goodsStatus == null ? null : goodsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.IS_DELETED
     *
     * @return the value of t_b2b_item.IS_DELETED
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.IS_DELETED
     *
     * @param isDeleted the value for t_b2b_item.IS_DELETED
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.CREATE_DATE
     *
     * @return the value of t_b2b_item.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.CREATE_DATE
     *
     * @param createDate the value for t_b2b_item.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.UPDATE_DATE
     *
     * @return the value of t_b2b_item.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.UPDATE_DATE
     *
     * @param updateDate the value for t_b2b_item.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.CREATE_USER
     *
     * @return the value of t_b2b_item.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.CREATE_USER
     *
     * @param createUser the value for t_b2b_item.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_item.UPDATE_USER
     *
     * @return the value of t_b2b_item.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_item.UPDATE_USER
     *
     * @param updateUser the value for t_b2b_item.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

	public String getSaleSum() {
		return saleSum;
	}

	public void setSaleSum(String saleSum) {
		this.saleSum = saleSum;
	}
    
    
    
}