package com.blgroup.jkl.bean;

import java.util.Date;

public class PurchaseApplyGoodsImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.APPLY_IMG_ID
     *
     * @mbggenerated
     */
    private Long applyImgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.APPLY_ID
     *
     * @mbggenerated
     */
    private Long applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.IMG_TYPE
     *
     * @mbggenerated
     */
    private String imgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.IMG_URL
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods_image.IS_DELETED
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.APPLY_IMG_ID
     *
     * @return the value of t_b2b_purchase_apply_goods_image.APPLY_IMG_ID
     *
     * @mbggenerated
     */
    public Long getApplyImgId() {
        return applyImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.APPLY_IMG_ID
     *
     * @param applyImgId the value for t_b2b_purchase_apply_goods_image.APPLY_IMG_ID
     *
     * @mbggenerated
     */
    public void setApplyImgId(Long applyImgId) {
        this.applyImgId = applyImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.APPLY_ID
     *
     * @return the value of t_b2b_purchase_apply_goods_image.APPLY_ID
     *
     * @mbggenerated
     */
    public Long getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.APPLY_ID
     *
     * @param applyId the value for t_b2b_purchase_apply_goods_image.APPLY_ID
     *
     * @mbggenerated
     */
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.IMG_TYPE
     *
     * @return the value of t_b2b_purchase_apply_goods_image.IMG_TYPE
     *
     * @mbggenerated
     */
    public String getImgType() {
        return imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.IMG_TYPE
     *
     * @param imgType the value for t_b2b_purchase_apply_goods_image.IMG_TYPE
     *
     * @mbggenerated
     */
    public void setImgType(String imgType) {
        this.imgType = imgType == null ? null : imgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.IMG_URL
     *
     * @return the value of t_b2b_purchase_apply_goods_image.IMG_URL
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.IMG_URL
     *
     * @param imgUrl the value for t_b2b_purchase_apply_goods_image.IMG_URL
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.CREATE_DATE
     *
     * @return the value of t_b2b_purchase_apply_goods_image.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.CREATE_DATE
     *
     * @param createDate the value for t_b2b_purchase_apply_goods_image.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.UPDATE_DATE
     *
     * @return the value of t_b2b_purchase_apply_goods_image.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.UPDATE_DATE
     *
     * @param updateDate the value for t_b2b_purchase_apply_goods_image.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.CREATE_USER
     *
     * @return the value of t_b2b_purchase_apply_goods_image.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.CREATE_USER
     *
     * @param createUser the value for t_b2b_purchase_apply_goods_image.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.UPDATE_USER
     *
     * @return the value of t_b2b_purchase_apply_goods_image.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.UPDATE_USER
     *
     * @param updateUser the value for t_b2b_purchase_apply_goods_image.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods_image.IS_DELETED
     *
     * @return the value of t_b2b_purchase_apply_goods_image.IS_DELETED
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods_image.IS_DELETED
     *
     * @param isDeleted the value for t_b2b_purchase_apply_goods_image.IS_DELETED
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}