package com.blgroup.jkl.bean;

import java.util.Date;

public class PurchaseOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.ORDER_ID
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.GOODS_ID
     *
     * @mbggenerated
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.SALE_SUM
     *
     * @mbggenerated
     */
    private Integer saleSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_order_detail.IS_DELETED
     *
     * @mbggenerated
     */
    private String isDeleted;

  private String barCode;
    
    

    public String getBarCode() {
		return barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.DETAIL_ID
     *
     * @return the value of t_b2b_purchase_order_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.DETAIL_ID
     *
     * @param detailId the value for t_b2b_purchase_order_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.ORDER_ID
     *
     * @return the value of t_b2b_purchase_order_detail.ORDER_ID
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.ORDER_ID
     *
     * @param orderId the value for t_b2b_purchase_order_detail.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.GOODS_ID
     *
     * @return the value of t_b2b_purchase_order_detail.GOODS_ID
     *
     * @mbggenerated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.GOODS_ID
     *
     * @param goodsId the value for t_b2b_purchase_order_detail.GOODS_ID
     *
     * @mbggenerated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.SALE_SUM
     *
     * @return the value of t_b2b_purchase_order_detail.SALE_SUM
     *
     * @mbggenerated
     */
    public Integer getSaleSum() {
        return saleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.SALE_SUM
     *
     * @param saleSum the value for t_b2b_purchase_order_detail.SALE_SUM
     *
     * @mbggenerated
     */
    public void setSaleSum(Integer saleSum) {
        this.saleSum = saleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.STATE
     *
     * @return the value of t_b2b_purchase_order_detail.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.STATE
     *
     * @param state the value for t_b2b_purchase_order_detail.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.CREATE_DATE
     *
     * @return the value of t_b2b_purchase_order_detail.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.CREATE_DATE
     *
     * @param createDate the value for t_b2b_purchase_order_detail.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.UPDATE_DATE
     *
     * @return the value of t_b2b_purchase_order_detail.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.UPDATE_DATE
     *
     * @param updateDate the value for t_b2b_purchase_order_detail.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.CREATE_USER
     *
     * @return the value of t_b2b_purchase_order_detail.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.CREATE_USER
     *
     * @param createUser the value for t_b2b_purchase_order_detail.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.UPDATE_USER
     *
     * @return the value of t_b2b_purchase_order_detail.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.UPDATE_USER
     *
     * @param updateUser the value for t_b2b_purchase_order_detail.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_order_detail.IS_DELETED
     *
     * @return the value of t_b2b_purchase_order_detail.IS_DELETED
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_order_detail.IS_DELETED
     *
     * @param isDeleted the value for t_b2b_purchase_order_detail.IS_DELETED
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}