package com.blgroup.jkl.bean;

import java.util.Date;
import java.util.List;

public class PurchaseApplyGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.APPLY_ID
     *
     * @mbggenerated
     */
    private Long applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.PUR_ID
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.BAR_CODE
     *
     * @mbggenerated
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.SALE_SUM
     *
     * @mbggenerated
     */
    private Integer saleSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_b2b_purchase_apply_goods.IS_DELETED
     *
     * @mbggenerated
     */
    private String isDeleted;

    
    private List<PurchaseApplyGoodsImage> purchaseApplyGoodsImageList;
    
    
    
    public List<PurchaseApplyGoodsImage> getPurchaseApplyGoodsImageList() {
		return purchaseApplyGoodsImageList;
	}

	public void setPurchaseApplyGoodsImageList(List<PurchaseApplyGoodsImage> purchaseApplyGoodsImageList) {
		this.purchaseApplyGoodsImageList = purchaseApplyGoodsImageList;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods.APPLY_ID
     *
     * @return the value of t_b2b_purchase_apply_goods.APPLY_ID
     *
     * @mbggenerated
     */
    public Long getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods.APPLY_ID
     *
     * @param applyId the value for t_b2b_purchase_apply_goods.APPLY_ID
     *
     * @mbggenerated
     */
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }



    public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods.BAR_CODE
     *
     * @return the value of t_b2b_purchase_apply_goods.BAR_CODE
     *
     * @mbggenerated
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods.BAR_CODE
     *
     * @param barCode the value for t_b2b_purchase_apply_goods.BAR_CODE
     *
     * @mbggenerated
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods.SALE_SUM
     *
     * @return the value of t_b2b_purchase_apply_goods.SALE_SUM
     *
     * @mbggenerated
     */
    public Integer getSaleSum() {
        return saleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods.SALE_SUM
     *
     * @param saleSum the value for t_b2b_purchase_apply_goods.SALE_SUM
     *
     * @mbggenerated
     */
    public void setSaleSum(Integer saleSum) {
        this.saleSum = saleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods.CREATE_DATE
     *
     * @return the value of t_b2b_purchase_apply_goods.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods.CREATE_DATE
     *
     * @param createDate the value for t_b2b_purchase_apply_goods.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods.UPDATE_DATE
     *
     * @return the value of t_b2b_purchase_apply_goods.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods.UPDATE_DATE
     *
     * @param updateDate the value for t_b2b_purchase_apply_goods.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods.CREATE_USER
     *
     * @return the value of t_b2b_purchase_apply_goods.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods.CREATE_USER
     *
     * @param createUser the value for t_b2b_purchase_apply_goods.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods.UPDATE_USER
     *
     * @return the value of t_b2b_purchase_apply_goods.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods.UPDATE_USER
     *
     * @param updateUser the value for t_b2b_purchase_apply_goods.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_b2b_purchase_apply_goods.IS_DELETED
     *
     * @return the value of t_b2b_purchase_apply_goods.IS_DELETED
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_b2b_purchase_apply_goods.IS_DELETED
     *
     * @param isDeleted the value for t_b2b_purchase_apply_goods.IS_DELETED
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}